CREATE TABLE `homework` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `END_DATE` datetime DEFAULT NULL,
  `EVALUATION_END_DATE` datetime DEFAULT NULL,
  `EVALUATION_START_DATE` datetime DEFAULT NULL,
  `META_DATA` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `START_DATE` datetime DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `TEACHER_REMARKS` varchar(255) DEFAULT NULL,
  `TYPE` varchar(255) DEFAULT NULL,
  `UPDATED_ON` datetime DEFAULT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `SUBJECT` bigint(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `TOTAL_MARKS` int(11) DEFAULT NULL,
  `SUBMISSION` varchar(20) DEFAULT NULL,
  `EVALUTION` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `homework_batch` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_ON` datetime DEFAULT NULL,
  `UPDATED_ON` datetime DEFAULT NULL,
  `BATCH_ID` bigint(20) DEFAULT NULL,
  `HOME_WORK_ID` bigint(20) DEFAULT NULL,
  `BATCH_NAME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_HOMEWORK_BATCH_HW_ID` (`HOME_WORK_ID`),
  CONSTRAINT `FK_HOMEWORK_BATCH_HW_ID` FOREIGN KEY (`HOME_WORK_ID`) REFERENCES `homework` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `homework_branch` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_ON` datetime DEFAULT NULL,
  `UPDATED_ON` datetime DEFAULT NULL,
  `BRANCH_ID` bigint(20) DEFAULT NULL,
  `HOME_WORK_ID` bigint(20) DEFAULT NULL,
  `BRANCH_NAME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_HOMEWORK_BRANCH_HW_ID` (`HOME_WORK_ID`),
  CONSTRAINT `FK_HOMEWORK_BRANCH_HW_ID` FOREIGN KEY (`HOME_WORK_ID`) REFERENCES `homework` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `homework_section` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_ON` datetime DEFAULT NULL,
  `UPDATED_ON` datetime DEFAULT NULL,
  `SECTION_ID` bigint(20) DEFAULT NULL,
  `HOME_WORK_ID` bigint(20) DEFAULT NULL,
  `SECTION_NAME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_HOMEWORK_SECTION_HW_ID` (`HOME_WORK_ID`),
  CONSTRAINT `FK_HOMEWORK_SECTION_HW_ID` FOREIGN KEY (`HOME_WORK_ID`) REFERENCES `homework` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `homework_grade` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_ON` datetime DEFAULT NULL,
  `UPDATED_ON` datetime DEFAULT NULL,
  `GRADE_ID` bigint(20) DEFAULT NULL,
  `HOME_WORK_ID` bigint(20) DEFAULT NULL,
  `GRADE_NAME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_HOMEWORK_GRADE_HW_ID` (`HOME_WORK_ID`),
  CONSTRAINT `FK_HOMEWORK_GRADE_HW_ID` FOREIGN KEY (`HOME_WORK_ID`) REFERENCES `homework` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `homework_orientation` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_ON` datetime DEFAULT NULL,
  `UPDATED_ON` datetime DEFAULT NULL,
  `ORIENTATION_ID` bigint(20) DEFAULT NULL,
  `HOME_WORK_ID` bigint(20) DEFAULT NULL,
  `ORIENTATION_NAME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_HOMEWORK_ORIENTATION_HW_ID` (`HOME_WORK_ID`),
  CONSTRAINT `FK_HOMEWORK_ORIENTATION_HW_ID` FOREIGN KEY (`HOME_WORK_ID`) REFERENCES `homework` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `assignment_section` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `HOME_WORK_ID` bigint(20) NOT NULL,
  `ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `POSITIVE_MARKS` float DEFAULT '0',
  `NEGATIVE_MARKS` float DEFAULT '0',
  `SECTION_NAME` varchar(255) DEFAULT NULL,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` datetime DEFAULT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `TOTAL_MARKS` float DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `FK94GXKTDPN8QTHJB7TUFFBFUTTT` (`HOME_WORK_ID`),
  CONSTRAINT `FK94GXKTDPN8QTHJB7TUFFBFUTTT` FOREIGN KEY (`HOME_WORK_ID`) REFERENCES `homework` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `assignment_result` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NEGATIVE_MARKS` float NOT NULL,
  `POSITIVE_MARKS` float NOT NULL,
  `TOTAL_MARKS` float NOT NULL,
  `UPDATED_ON` datetime DEFAULT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `ASSIGNMENT_ID` bigint(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `CORRECT` mediumint(5) DEFAULT '0',
  `WRONG` mediumint(5) DEFAULT '0',
  `UNATTEMPTED` mediumint(5) DEFAULT '0',
  `ASSIGNMENT_SECTION_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKIS4K3UDGYWT7S44LD234CKLJ8` (`ASSIGNMENT_ID`),
  KEY `FK_ASSIGN_RESULT_ID` (`ASSIGNMENT_SECTION_ID`),
  CONSTRAINT `FK_ASSIGN_RESULT_ID` FOREIGN KEY (`ASSIGNMENT_SECTION_ID`) REFERENCES `assignment_section` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `student_assignment` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ATTEMPT_COUNT` bigint(20) DEFAULT NULL,
  `ATTEMPT_END_TIME` datetime DEFAULT NULL,
  `ATTEMPT_START_TIME` datetime DEFAULT NULL,
  `IS_COMPLETED` tinyint(1) DEFAULT NULL,
  `META_DATA` varchar(255) DEFAULT NULL,
  `HOMEWORK_ID` bigint(20) DEFAULT NULL,
  `RESULT_ID` bigint(20) DEFAULT NULL,
  `FEEDBACK` varchar(255) DEFAULT NULL,
  `COMMENTS` varchar(255) DEFAULT NULL,
  `STUDENT_ID` varchar(20) DEFAULT NULL,
  `DOWNLOAD_COUNT` bigint(20) DEFAULT NULL,
  `REMARKS` varchar(200) DEFAULT NULL,
  `UPDATED_ON` datetime DEFAULT NULL,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKTOT1FBWSUVUPU0M81FC1N2EN2` (`STUDENT_ID`),
  KEY `FK8DIWFVLARFVN7B99L3NQVB32O` (`HOMEWORK_ID`),
  KEY `FKG9UXL1846PC7YKWPHQPVNGGT` (`RESULT_ID`),
  CONSTRAINT `FK8DIWFVLARFVN7B99L3NQVB32O` FOREIGN KEY (`HOMEWORK_ID`) REFERENCES `homework` (`ID`),
  CONSTRAINT `FKG9UXL1846PC7YKWPHQPVNGGT` FOREIGN KEY (`RESULT_ID`) REFERENCES `assignment_result` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `assignment_file` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LOCATION` varchar(500) DEFAULT NULL,
  `UPDATED_ON` datetime DEFAULT NULL,
  `ASSIGNMENT_ID` bigint(20) DEFAULT NULL,
  `REMARKS` varchar(500) DEFAULT NULL,
  `FILE_LOCATION` varchar(255) DEFAULT NULL,
  `FILE_SIZE` double DEFAULT NULL,
  `FILE_DOWNLOAD_COUNT` bigint(20) DEFAULT NULL,
  `FILE_TYPE` varchar(250) DEFAULT NULL,
  `IS_ACTIVE` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`ID`),
  KEY `FKJGSPL1XKTJIUTM1MK12RQUM8K` (`ASSIGNMENT_ID`),
  CONSTRAINT `FKJGSPL1XKTJIUTM1MK12RQUM8K` FOREIGN KEY (`ASSIGNMENT_ID`) REFERENCES `student_assignment` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `assignment_file_comments` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` datetime DEFAULT NULL,
  `ASSIGNMENT_FILE_ID` bigint(20) DEFAULT NULL,
  `COMMENTS` varchar(500) DEFAULT NULL,
  `ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ASSIGNMENT_FILE_CMNT_ID` (`ASSIGNMENT_FILE_ID`),
  CONSTRAINT `FK_ASSIGNMENT_FILE_CMNT_ID` FOREIGN KEY (`ASSIGNMENT_FILE_ID`) REFERENCES `assignment_file` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `assignment_questions` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `QUESTION_ID` varchar(100) DEFAULT NULL,
  `MARKS` bigint(20) DEFAULT NULL,
  `ASSIGNMENT_SECTION_ID` bigint(20) DEFAULT NULL,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` datetime DEFAULT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `IS_MYLIBRARY` bit(1) DEFAULT b'0',
  PRIMARY KEY (`ID`),
  KEY `FK_ASSIGN_QUES_SEC_ID` (`ASSIGNMENT_SECTION_ID`),
  CONSTRAINT `FK_ASSIGN_QUES_SEC_ID` FOREIGN KEY (`ASSIGNMENT_SECTION_ID`) REFERENCES `assignment_section` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;





CREATE TABLE `customercare` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ISSUE` varchar(255) DEFAULT NULL,
  `ISSUE_STATUS` varchar(255) DEFAULT NULL,
  `ISSUE_TYPE` varchar(255) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `USER_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;







CREATE TABLE `homework_files` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LOCATION` varchar(500) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `UPDATED_ON` datetime DEFAULT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `HOME_WORK_ID` bigint(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `MARKS` double DEFAULT NULL,
  `FILE_NAME` varchar(255) DEFAULT NULL,
  `FILE_SIZE` float DEFAULT NULL,
  `FILE_TYPE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK94GXKTDPN8QTHJB7TUFFBFUMFF` (`HOME_WORK_ID`),
  CONSTRAINT `FK94GXKTDPN8QTHJB7TUFFBFUMFF` FOREIGN KEY (`HOME_WORK_ID`) REFERENCES `homework` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;




CREATE TABLE `notification` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `IMAGE_PATH` varchar(255) DEFAULT NULL,
  `TYPE` varchar(255) DEFAULT NULL,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `TITLE` varchar(255) DEFAULT NULL,
  `UPDATED_ON` datetime DEFAULT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `question_type` (
  `QUESTION_TYPE_ID` mediumint(9) NOT NULL AUTO_INCREMENT,
  `QUESTION_TYPE` varchar(30) NOT NULL,
  `STATUS` tinyint(1) DEFAULT '0',
  `CREATED_ON` datetime DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_ON` datetime DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`QUESTION_TYPE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `question` (
  `QUESTION_ID` mediumint(9) NOT NULL AUTO_INCREMENT,
  `TEXT` longtext NOT NULL,
  `POSITIVE_MARKS` float DEFAULT '0.0',
  `NEGATIVE_MARKS` float DEFAULT '0.0',
  `SOLUTION` longtext,
  `HINT` longtext,
  `QUESTION_TYPE_ID` mediumint(9) NOT NULL,
  `QUESTION_STATUS` varchar(200) DEFAULT NULL,
  `SUBJECT_ID` bigint(20) NOT NULL,
  `ASSING_SECTION_ID` bigint(20) NOT NULL,
  `UUID` varchar(50) NOT NULL,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_ON` datetime DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`QUESTION_ID`),
  KEY `FK_QUESTION_TYPE_ID` (`QUESTION_TYPE_ID`),
  KEY `FK_QUESTION_SECTION_ID` (`ASSING_SECTION_ID`),
  CONSTRAINT `FK_QUESTION_SECTION_ID` FOREIGN KEY (`ASSING_SECTION_ID`) REFERENCES `assignment_section` (`ID`),
  CONSTRAINT `FK_QUESTION_TYPE_ID` FOREIGN KEY (`QUESTION_TYPE_ID`) REFERENCES `question_type` (`QUESTION_TYPE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `question_option` (
  `ID` mediumint(9) NOT NULL AUTO_INCREMENT,
  `QUESTION_OPTION` longtext NOT NULL,
  `QUESTION_ID` mediumint(9) NOT NULL,
  `ANSWER` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `FK_QUESTION_ID` (`QUESTION_ID`),
  CONSTRAINT `FK_QUESTION_ID` FOREIGN KEY (`QUESTION_ID`) REFERENCES `question` (`QUESTION_ID`)
) ENGINE=InnoDB  AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;



CREATE TABLE `student` (
  `ADM_NO` varchar(255) NOT NULL,
  `CREATEDON` datetime DEFAULT NULL,
  `DOUBTS` varchar(255) DEFAULT NULL,
  `EMAIL_ID` varchar(255) DEFAULT NULL,
  `META_DATA` varchar(255) DEFAULT NULL,
  `MOBILE_NO` bigint(20) DEFAULT NULL,
  `PERMANENT_ADDRESS` varchar(255) DEFAULT NULL,
  `PRESENT_ADDRESS` varchar(255) DEFAULT NULL,
  `STATE` varchar(255) DEFAULT NULL,
  `UPDATEDON` datetime DEFAULT NULL,
  `CREATEDBY` varchar(20) DEFAULT NULL,
  `UPDATEDBY` varchar(20) DEFAULT NULL,
  `NAME` varchar(100) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;



CREATE TABLE `student_assignment_questions` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CORRECT` bit(1) NOT NULL,
  `CLEAR_RESPONSE` bit(1) NOT NULL,
  `MARK_FOR_REVIEW` bit(1) NOT NULL,
  `IS_VISITED` bit(1) NOT NULL,
  `RESPONSE` varchar(20) DEFAULT NULL,
  `ASSIGNMENT_QUESTION_ID` bigint(20) DEFAULT NULL,
  `STUDENT_ASSIGNMENT_ID` bigint(20) DEFAULT NULL,
  `QUESTION_GAP` bigint(20) DEFAULT NULL,
  `ATTEMPT_TIME` datetime DEFAULT NULL,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` datetime DEFAULT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `MARKS` float DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_STD_ASSIGN_QUESTION_ID` (`ASSIGNMENT_QUESTION_ID`),
  KEY `FK_STD_ASSIGNMENT_ID` (`STUDENT_ASSIGNMENT_ID`),
  CONSTRAINT `FK_STD_ASSIGNMENT_ID` FOREIGN KEY (`STUDENT_ASSIGNMENT_ID`) REFERENCES `student_assignment` (`ID`),
  CONSTRAINT `FK_STD_ASSIGN_QUESTION_ID` FOREIGN KEY (`ASSIGNMENT_QUESTION_ID`) REFERENCES `assignment_questions` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `student_feedback` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ADM_NO` varchar(20) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `TITLE` varchar(20) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `LOCATION` varchar(500) DEFAULT NULL,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `FILENAME` varchar(255) DEFAULT NULL,
  `FILE_SIZE` double DEFAULT NULL,
  `FILE_TYPE` varchar(50) DEFAULT NULL,
  `UPDATED_ON` datetime DEFAULT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `subject` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` varchar(255) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `UPDATED_ON` datetime DEFAULT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `user_notification` (
  `USER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_REPEATE` tinyint(1) DEFAULT NULL,
  `POST_DATE` varchar(255) DEFAULT NULL,
  `REPEATEDTIMER` varchar(255) DEFAULT NULL,
  `UPDATED_ON` datetime DEFAULT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `NOTIFICATION_ID` bigint(20) DEFAULT NULL,
  `STUDENT` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  KEY `FK476X4VMKOJR14I3IHRXXVFBM4` (`STUDENT`),
  KEY `FK1DXMM5RB61UWUWQNK07SJW5I4` (`NOTIFICATION_ID`),
  CONSTRAINT `FK1DXMM5RB61UWUWQNK07SJW5I4` FOREIGN KEY (`NOTIFICATION_ID`) REFERENCES `notification` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

